### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Marwa199527** [dksifoua/Question-Answering#6]
**Thank you for your work :)**
I was reading the DrQA paper and I saw this phrase " i ≤ i 0 ≤ i + max len", so my question is how to make sure that the model will predict a start index that is less than the end index in the training and testing
 please answer my question, thank you in advance!

**Comment by dksifoua** [comment]
Hi @Marwa199527,

The model predicts the probability for each word indice in the paragraph input to be the start or the end. And we just have the max proba. This ensures " i ≤ i 0 ≤ i + max len".

Hope its helps you!
